super/apps/commodity/urls.py
from django.conf.urls import url

from commodity.views import IndexView, DetailView, CategoryView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='主页'),
    url(r'^detail$', DetailView.as_view(), name='详情'),
    url(r'^category$', CategoryView.as_view(), name='超市'),

]

super/apps/user/urls.py
from django.conf.urls import url

from user.views import RegView, LoginView, UserView, UserInfoView, SendMeg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="登录"),
    url(r'^reg/$', RegView.as_view(), name="注册"),
    url(r'^member/$', UserView.as_view(), name='个人中心'),
    url(r'^info/$', UserInfoView.as_view(), name='个人资料'),
    url(r'^senMsg/$', SendMeg.as_view(), name='短信验证')
]

super/super/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from commodity.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^order/', include('order.urls', namespace="order")),
    url(r'^commodity/', include('commodity.urls', namespace="commodity")),
    url(r'^shopping/', include('shopping.urls', namespace="shopping")),
    url(r'^$', IndexView.as_view()),
]

super/apps/commodity/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.core.validators import MinLengthValidator
# Create your models here.
# 商品分类表
from DB.base_model import BaseModel

is_on_sale_choices = (
    (False, "下架"),
    (True, "上架"),
)


class ComClassModel(BaseModel):
    class_name = models.CharField(
        max_length=50,
        verbose_name="分类名称",
        validators=[MinLengthValidator(2)],
    )
    class_intro = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name="分类简介"
    )

    class Meta:
        db_table = 'ComClassModel'
        verbose_name = '商品分类表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.class_name


class ComSpuModel(BaseModel):
    SPU_name = models.CharField(max_length=50,
                                validators=[MinLengthValidator(2)],
                                verbose_name='spu名称')
    SPU_details = RichTextUploadingField(max_length=500,
                                         validators=[MinLengthValidator(2)],
                                         verbose_name='spu详情')

    class Meta:
        db_table = 'ComSpuModel'
        verbose_name = '商品SPU表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.SPU_name


class UnitModel(BaseModel):
    unit = models.CharField(max_length=10,
                            verbose_name='单位')

    class Meta:
        db_table = 'UnitModel'
        verbose_name = '商品单位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.unit


class ComSkuModel(BaseModel):
    Sku_name = models.CharField(max_length=50,
                                validators=[MinLengthValidator(2)],
                                verbose_name='商品名')
    comintro = models.CharField(max_length=100,
                                validators=[MinLengthValidator(2)],
                                verbose_name='商品简介')

    price = models.DecimalField(max_digits=10,
                                decimal_places=2,
                                verbose_name='价格')
    stock = models.PositiveIntegerField(verbose_name='库存')
    sales = models.PositiveIntegerField(verbose_name='销量')
    logo = models.ImageField(verbose_name='封面图片', upload_to='logo/%Y%m/%d')
    is_on_sale = models.BooleanField(verbose_name="是否上架",
                                     choices=is_on_sale_choices, default=False)
    Comclass = models.ForeignKey(to="ComClassModel",
                                 verbose_name="商品分类")
    Com_spu = models.ForeignKey(to="ComSpuModel", verbose_name="商品SPU")

    def __str__(self):
        return self.Sku_name

    class Meta:
        verbose_name = "商品SKU管理"
        verbose_name_plural = verbose_name


class GalleryModel(BaseModel):
    img_url = models.ImageField(verbose_name='图集图片地址', upload_to='gallery/%Y%m/%d')
    com_sku = models.ForeignKey(to='ComSkuModel', verbose_name='商品SKU')

    class Meta:
        verbose_name = '商品图集管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "商品图集:{}".format(self.img_url.name)


class BannerModel(BaseModel):
    name = models.CharField(verbose_name="轮播活动",
                            max_length=50, )
    img_url = models.ImageField(verbose_name="轮播图片地址",
                                upload_to='banner/%Y%m/%d')
    order = models.SmallIntegerField(verbose_name="排序", default=0)
    com_sku = models.ForeignKey(to="ComSkuModel", verbose_name="商品SKU")

    class Meta:
        verbose_name = "轮播管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ActivityModel(BaseModel):
    Activi_name = models.CharField(verbose_name='活动名称', max_length=50)
    Activi_image = models.ImageField(verbose_name='活动图片地址', upload_to='activity/%Y%m/%d')
    Activi_url = models.URLField(verbose_name='活动的url地址', max_length=255)

    def __str__(self):
        return self.Activi_name

    class Meta:
        verbose_name = '活动管理'
        verbose_name_plural = verbose_name


class ActivityZoneModel(BaseModel):
    AZ_name = models.CharField(verbose_name="活动专区名称", max_length=50)
    AZ_intro = models.CharField(verbose_name="活动专区简介", max_length=255, null=True, blank=True)
    AZ_order = models.SmallIntegerField(verbose_name="排序", default=0)
    is_on_sale = models.BooleanField(verbose_name="是否上线", choices=is_on_sale_choices, default=0)
    com_sku = models.ManyToManyField(to="ComSkuModel", verbose_name="商品")

    def __str__(self):
        return self.AZ_name

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name

super/apps/commodity/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View


class IndexView(View):
    def get(self, request):

        return render(request, 'commodity/index.html')

    def post(self, request):
        pass


class DetailView(View):
    def get(self, request):
        return render(request, 'commodity/detail.html')

    def post(self, request):
        pass


class CategoryView(View):
    def get(self, request):
        return render(request, 'commodity/category.html')

    def post(self, request):
        pass

super/templates/commodity/category.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    商品详情
{% endblock %}
{% block head_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }
    </style>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <input type="text" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
            <input type="button" class="cate-btn"/>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li class="current"><a href="">综合</a></li>
        <li><a href="">销量</a></li>
        <li><a href=""><i class="list-price">价格</i></li>
        <li><a href="">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            <li><a href="">进口特产</a></li>
            <li class="current"><a href="">休闲零食</a></li>
            <li><a href="">糖果饼干</a></li>
            <li><a href="">饮料牛奶</a></li>
            <li><a href="">方便速食</a></li>
            <li><a href="">生活用品</a></li>
            <li><a href="">香烟代购</a></li>
            <li><a href="">水果酸奶便当</a></li>
        </div>
        <div class="list-right">
            <ul class="list-pro">
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src="{% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="{% url 'commodity:详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="{% url 'commodity:详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src="{% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="{% url 'commodity:详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>
                <li>
                    <a href="{% url 'commodity:详情' %}"><img src=" {% static 'images/test10.png' %}" class="list-pic"/></a>
                    <div class="shop-list-mid" style="width: 65%;">
                        <div class="tit"><a href="{% url 'commodity:详情' %}">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                        <div class="am-gallery-desc">￥52</div>
                        <p>销量：5件</p>
                    </div>
                    <div class="list-cart">
                        <div class="d-stock ">
                            <a class="decrease">-</a>
                            <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                            <a class="increase">+</a>
                        </div>
                    </div>
                    <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                </li>

            </ul>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <div class="fix-bot-cart"><i>8</i></div>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                if (current_num > 0) {
                    self.siblings(".decrease").fadeIn();
                    self.siblings(".text_box").fadeIn();
                }
                self.siblings('input').val(current_num);
                update_item(self.siblings('input').data('item-id'));
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {
                    current_num -= 1;
                    if (current_num < 1) {
                        self.fadeOut();
                        self.siblings(".text_box").fadeOut();
                    }
                    self.siblings('input').val(current_num);
                    update_item(self.siblings('input').data('item-id'));
                }
            })
        })

    </script>
{% endblock %}

super/templates/commodity/index.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    超市
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head1">
        <div class="am-header-left am-header-nav">
            <a href="city.html" class="" style="color: #fff;">
                <img src="{% static 'images/city.png' %}"/>
                <p style="font-size: 12px; margin-top: -35px;" id="info">全国</p>
            </a>
        </div>
        <h1 class="am-header-title1">
            <div class="search-box">
                <a href="village.html" class="index-search">成都大学前湖校区</a>
                <!--  <input type="submit" value="" class="search-icon" /> -->
            </div>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="tidings.html" class="">
                <div class="messgae"><span>10</span></div>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}
{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            <li><img src="{% static 'media/banner/201901/24/computer.jpg' %}"/></li>
            <li><img src="{% static 'media/banner/201901/24/phone_index.jpg' %}"/></li>
            <li><img src="{% static 'media/banner/201901/24/TV.jpg' %}"/></li>

        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="recharge.html" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="speed.html" class="">
                    <img src="{% static 'images/icon4.png' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:超市' %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        <div class="index-pro-lf"><a href=""><img src="{% static 'images/s1.png' %}"/></a></div>
        <div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"/></a></div>
    </div>
    <div class="product-bot">
        <div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
        <div class="product-bot-lr">
            <div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
            <div class="bot">
                <div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
                <div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
            </div>
        </div>
    </div>
    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->
    <div class="sq-title">
        <img src="{% static 'images/ts.png' %}" width="26"/>
        特色专区
    </div>
    <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test.png' %}"/>
                    <h3 class="am-gallery-title">猪骨头棒新鲜生鲜肉制品猪大骨头筒骨熬汤佳品500g</h3>
                    <div class="am-gallery-desc">￥52</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test1.png' %}"/>
                    <h3 class="am-gallery-title">冻品批发大江鸡腿 冷鲜鸡腿放心食材1kg 冷冻食材</h3>
                    <div class="am-gallery-desc">￥39</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test2.png' %}"/>
                    <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                    <div class="am-gallery-desc">￥45.8</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test21.png' %}"/>
                    <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                    <div class="am-gallery-desc">￥45.8</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test.png' %}"/>
                    <h3 class="am-gallery-title">猪骨头棒新鲜生鲜肉制品猪大骨头筒骨熬汤佳品500g</h3>
                    <div class="am-gallery-desc">￥52</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test1.png' %}"/>
                    <h3 class="am-gallery-title">冻品批发大江鸡腿 冷鲜鸡腿放心食材1kg 冷冻食材</h3>
                    <div class="am-gallery-desc">￥39</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test2.png' %}"/>
                    <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                    <div class="am-gallery-desc">￥45.8</div>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'commodity:详情' %}" class="">
                    <img src=" {% static 'images/test21.png' %}"/>
                    <h3 class="am-gallery-title">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</h3>
                    <div class="am-gallery-desc">￥45.8</div>
                </a>
            </div>
        </li>
    </ul>
    <!--签到-->
    <div class="qd-box">
        <div class="popup-title">
            <span>签到成功</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <img src="{% static 'images/qiandao.png' %}" width="40"/>&nbsp; 您已连续签到3天
        </div>
    </div>
    <!--签到-->
{% endblock %}

{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'user:个人中心' %}" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}


{% block footer_js %}
<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.12&key=5b9ea05eb54960a0d39f0f7bd2fb245d&plugin=AMap.CitySearch"></script>
<script type="text/javascript">
    //获取用户所在城市信息
    function showCityInfo() {
        //实例化城市查询类
        var citysearch = new AMap.CitySearch();
        //自动获取用户IP，返回当前城市
        citysearch.getLocalCity(function(status, result) {
            if (status === 'complete' && result.info === 'OK') {
                if (result && result.city && result.bounds) {
                    var cityinfo = result.city;
                    document.getElementById('info').innerHTML = cityinfo;
                }
            } else {
                document.getElementById('info').innerHTML = result.info;
            }
        });
    }
    showCityInfo();
</script>
{% endblock %}

 
 
 