super/apps/user/urls.py
from django.conf.urls import url

from user.views import RegView, LoginView, UserView, UserInfoView, SendMeg

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="登录"),
    url(r'^reg/$', RegView.as_view(), name="注册"),
    url(r'^member/$', UserView.as_view(), name='个人中心'),
    url(r'^info/$', UserInfoView.as_view(), name='个人资料'),
    url(r'^senMsg/$', SendMeg.as_view(), name='短信验证')
]

super/super/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from commodity.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^user/', include('user.urls', namespace="user")),
    url(r'^order/', include('order.urls', namespace="order")),
    url(r'^commodity/', include('commodity.urls', namespace="commodity")),
    url(r'^shopping/', include('shopping.urls', namespace="shopping")),
    url(r'^$', IndexView.as_view()),
]

super/apps/user/models.py
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models


# Create your models here.


class MarketUsers(models.Model):
    sex_choices = {
        (1, "男"),
        (2, "女"),
    }
    phone = models.CharField(max_length=11,
                             verbose_name="手机号码",
                             validators=[
                                 RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误!")
                             ])
    nick_name = models.CharField(max_length=50,
                                 null=True,
                                 blank=True,
                                 verbose_name="昵称"
                                 )
    password = models.CharField(max_length=32,
                                verbose_name="密码"
                                )
    gender = models.SmallIntegerField(choices=sex_choices,
                                      default=2,
                                      verbose_name="性别")
    birthday = models.DateField(null=True,
                                blank=True,
                                verbose_name="生日"
                                )
    school = models.CharField(max_length=50,
                              null=True,
                              blank=True,
                              verbose_name="学校")
    hometown = models.CharField(max_length=50,
                                null=True,
                                blank=True,
                                verbose_name="家庭地址")
    address = models.CharField(max_length=255,
                               null=True,
                               blank=True,
                               verbose_name="住址")
    head = models.ImageField(upload_to="head/%Y%m", default='head/memtx.png')

    def __str__(self):
        return self.phone

    class Meta:
        db_table = 'mk_users'
        verbose_name = "用户管理"
        verbose_name_plural = verbose_name

super/apps/user/forms.py
from django import forms

from user.helper import set_password
from user.models import MarketUsers
from django_redis import get_redis_connection



class RegModelForm(forms.ModelForm):
    password = forms.CharField(max_length=16,
                               min_length=6,
                               error_messages={
                                   'required': '密码未填写',
                                   'max_length': '密码长度不能大于16个字符',
                                   'min_length': '密码长度不能小于6个字符'
                               })
    repassword = forms.CharField(error_messages={
        'required': '确认密码未填写'
    })

    captcha = forms.CharField(max_length=6,
                              min_length=6,
                              error_messages={
                                  'required': '验证码未填写',
                                  'max_length': '验证码格式错误',
                                  'min_length': "验证码格式错误"
                              })
    agree = forms.BooleanField(error_messages={
        'required': '必须同意用户协议'
    })

    class Meta:
        model = MarketUsers
        # 需要验证的字段
        fields = ['phone', ]

        error_messages = {
            "phone": {
                'required': "手机号码未填写"
            }
        }

    def clean_phone(self):
        # 验证手机号码是否唯一
        phone = self.cleaned_data.get('phone')
        rs = MarketUsers.objects.filter(phone=phone).exists()
        if rs:
            raise forms.ValidationError("该手机号码已被注册")
        return phone
        # 单独清洗

    def clean(self):
        # 验证密码是否一致
        password = self.cleaned_data.get("password")
        repassword = self.cleaned_data.get("repassword")

        if password and repassword and password != repassword:
            # 确认密码错误
            raise forms.ValidationError({"repassword": "两次密码输入不一致"})
        # 综合校验
        try:
            captcha = self.cleaned_data.get('captcha')
            phone = self.cleaned_data.get('phone','')
            r = get_redis_connection()
            random_code = r.get(phone)
            random_code = random_code.decode('utf-8')  # 获取到的验证码是二进制 要转码
            if captcha and captcha != random_code:
                raise forms.ValidationError({'captcha': '验证码输入错误'})
        except:
            raise forms.ValidationError({'captcha': '验证码输入错误'})

        # 返回清洗后的数据
        return self.cleaned_data


class LoginModelForm(forms.ModelForm):
    class Meta:
        model = MarketUsers
        fields = ['phone', 'password']

        error_messages = {
            'phone': {
                'required': '请填写手机号'
            },
            'password': {
                'required': '请填写密码'
            }
        }

    def clean(self):
        phone = self.cleaned_data.get('phone')
        password = self.cleaned_data.get('password')
        try:
            user = MarketUsers.objects.get(phone=phone)
        except MarketUsers.DoesNotExist:
            raise forms.ValidationError({'phone': '手机号码错误'})
        if user.password != set_password(password):
            raise forms.ValidationError({'password': '密码错误'})
        self.cleaned_data['user'] = user
        return self.cleaned_data

    # def clean(self):
    #     nick_name = self.cleaned_data.get('nick_name')
    #     birthday = self.cleaned_data.get('birthday')
    #     school = self.cleaned_data.get('school')
    #     address = self.cleaned_data.get('address')
    #     hometown = self.cleane`d_data.get('hometown')
    #     phone = self.cleaned_data.get('phone')
    #     self.cleaned_data['info'] = info
    # phone = self.cleaned_data.get('phone')
    # try:
    #     user = MarketUsers.objects.get(phone=phone)
    # except MarketUsers.DoesNotExist:
    #     raise forms.ValidationError({'phone': '手机号码错误'})
    # password = self.cleaned_data.get('password', '')
    # if user.password != set_password(password):
    #     raise forms.ValidationError({'password': '密码错误'})
    # self.cleaned_data['user'] = user
    # return self.cleaned_data

super/apps/user/views.py
import random
import uuid

from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.utils.decorators import method_decorator
from django.views import View

# 定义登录页面的视图
from user.forms import RegModelForm, LoginModelForm
from user.helper import set_password, login, check_login, send_sms
import re
from user.models import MarketUsers
from django_redis import get_redis_connection


class RegView(View):
    def get(self, request):
        return render(request, 'user/reg.html')

    def post(self, request):
        # 接收参数
        data = request.POST
        # 验证数据合法性
        register_form = RegModelForm(data)
        if register_form.is_valid():
            # 操作数据库
            # 获取清洗后的数据
            cleand_data = register_form.cleaned_data
            # 保存
            user = MarketUsers()
            user.phone = cleand_data.get('phone')
            user.password = set_password(cleand_data.get('password'))
            user.save()
            return redirect('user:登录')
        else:
            return render(request, 'user/reg.html', {"form": register_form})


class LoginView(View):
    def get(self, request):
        # 跳转登录页
        return render(request, 'user/login.html')

    def post(self, request):
        # 接受参数
        data = request.POST
        # 验证表单合法
        form = LoginModelForm(data)
        if form.is_valid():

            user = form.cleaned_data['user']
            login(request, user)

            return redirect('user:个人中心')
        else:
            return render(request, 'user/login.html', context={'form': form})


class UserView(View):
    # @method_decorator(check_login)
    def get(self, request):
        return render(request, 'user/member.html')

    # @method_decorator(check_login)
    def post(self, request):
        pass


class UserInfoView(View):
    def get(self, request):
        userinfo = MarketUsers.objects.get(pk=id)
        context = {
            'userinfo': userinfo
        }
        return render(request, 'user/infor.html', context=context)

    def post(self, request):
        data = request.POST
        id = data.get('id')
        MarketUsers.objects.filter(id=id).update(**data)
        return redirect('user:个人资料', )


class SendMeg(View):
    def get(self, request):
        pass

    def post(self, request):
        # 接受参数
        phone = request.POST.get('phone', '')
        rs = re.search('^1[3-9]\d{9}$', phone)
        # 判断参数合法性 如果合法返回一个对象不合法返回None
        if rs is None:
            return JsonResponse({'error': 1, 'errmsg': '手机号码格式不正确'})
        # # 操作数据
        # # 生成随机验证码进行模拟验证
        random_code = "".join([str(random.randint(0, 9)) for _ in range(6)])
        # print("随机验证码为{}".format(random_code))
        # # 保存验证码到redis中
        # r = get_redis_connection()
        # # 保存手机号对应的验证码
        # r.set(phone, random_code)
        # # 设置10分钟后过期
        # r.expire(phone, 600)
        # # 获取手机号发送验证码的次数
        # code_times = "{}_times".format(phone)
        # now_time = r.get(code_times)
        # if now_time is None or now_time < 5:
        #     # 发送验证码次数不存在或小于5
        #     r.incr(code_times)
        #     # 设置10分钟后过期
        #     r.expire(code_times, 600)
        # else:
        #     # 返回错误 告知用户验证码发送次数过多
        #     return JsonResponse({"error": 1, "errmsg": "验证码发送次数过多"})
        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\" 我主良缘婚介所 \"}" % random_code
        # print(params)
        rs = send_sms(__business_id, phone, "注册验证", "SMS_2245271", params)
        print(rs.decode('utf-8'))

        # 合成响应

        return JsonResponse({'error': 0})

super/templates/user/allorder.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<link href="css/check.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">全部订单</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="order-style">
	    	<li class="current"><a href="allorder.html">全部</a></li>
	    	<li><a href="allorder.html">待付款</a></li>
	    	<li><a href="allorder.html">退发货</a></li>
	    	<li><a href="allorder.html">待收货</a></li>
	    	<li><a href="allorder.html">待评价</a></li>

	    </ul>
	    <!--代付款-->
	    <div class="c-comment">
			<span class="c-comment-num">支付宝支付</span>
			<span class="c-comment-suc">待付款</span>
		</div>
		
		<div class="c-comment-list" style="border: 0;">
			<a href="orderdetail.html">
			<p>应付金额：￥63.0     实付金额：<span>￥63.0</span></p>
			<p>订单编号：123456789</p>
			<p>下单时间：2016-01-07  10：22：52</p>
			<p>联系店长：沫沫       <span><i class="iconfont">&#xe603</i>18012345678</span></p>
            </a>
		</div>
		<div class="c-com-btn">
			<a href="tureorder.html" class="oncepay">立即支付</a>
			<a href="" class="canelpay">取消订单</a>
		</div>
		<div class="clear"></div>
		<!--代付款-->
		<!--待收货-->
		 <div class="c-comment">
			<span class="c-comment-num">微信支付</span>
			<span class="c-comment-suc">待收货</span>
		</div>
		
		<div class="c-comment-list" style="border: 0;">
			<a href="orderdetail.html">
			<p>应付金额：￥63.0     实付金额：<span>￥63.0</span> <b>省</b><span>￥2.5</span> </p>
			<p>订单编号：123456789</p>
			<p>下单时间：2016-01-07  10：22：52</p>
			<p>联系店长：沫沫       <span><i class="iconfont">&#xe603</i>18012345678</span></p>
			</a>
		</div>
		<div class="c-com-btn">
			<a href="" class="oncepay">确认收货</a>
			<a href="" class="canelpay">取消订单</a>
		</div>
		<div class="clear"></div>
		<!--待收货-->
		<!--交易成功-->
		 <div class="c-comment">
			<span class="c-comment-num">余额支付</span>
			<span class="c-comment-suc">已完成</span>
		</div>
		
		<div class="c-comment-list" style="border: 0;">
			<a href="orderdetail.html">
			<p>应付金额：￥63.0     实付金额：<span>￥63.0</span> <b>省</b><span>￥2.5</span> </p>
			<p>订单编号：123456789</p>
			<p>下单时间：2016-01-07  10：22：52</p>
			<p>联系店长：沫沫       <span><i class="iconfont">&#xe603</i>18012345678</span></p>
			</a>
		</div>
		<div class="c-com-btn">
			<a href="" class="oncepay">删除订单</a>
			<a href="" class="canelpay">投诉</a>
		</div>
		<div class="clear"></div>
		<!--交易成功-->
		<!--交易成功-->
		 <div class="c-comment">
			<span class="c-comment-num">余额支付</span>
			<span class="c-comment-suc">待发货</span>
		</div>
		
		<div class="c-comment-list" style="border: 0;">
			<a href="orderdetail.html">
			<p>应付金额：￥63.0     实付金额：<span>￥63.0</span> <b>省</b><span>￥2.5</span> </p>
			<p>订单编号：123456789</p>
			<p>下单时间：2016-01-07  10：22：52</p>
			<p>联系店长：沫沫       <span><i class="iconfont">&#xe603</i>18012345678</span></p>
			</a>
		</div>
		<div class="c-com-btn">
			<a href="" class="canelpay">取消订单</a>
		</div>
		<div class="clear"></div>
		<!--交易成功-->
		<div class="c-comment">
			<span class="c-comment-num">余额支付</span>
			<span class="c-comment-suc"> 待评价</span>
		</div>
		
		<div class="c-comment-list" style="border: 0;">
			<a href="orderdetail.html">
			<p>应付金额：￥63.0     实付金额：<span>￥63.0</span> <b>省</b><span>￥2.5</span> </p>
			<p>订单编号：123456789</p>
			<p>下单时间：2016-01-07  10：22：52</p>
			<p>联系店长：沫沫       <span><i class="iconfont">&#xe603</i>18012345678</span></p>
			</a>
		</div>
		<div class="c-com-btn">
			<a href="" class="oncepay">立即评价</a>
		</div>
		
		  <!--底部-->
 <div style="height:55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">   
          <li>
            <a href="index.html" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="curr">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>
 
          <li>
            <a href="member.html" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>
 
	</body>
</html>

super/templates/user/forgetpassword.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<script src="js/jquery-1.10.2.min.js"></script>
	</head>
	<body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">忘记密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>

	    <input type="text" name="mobile"  placeholder="请输入手机号" class="login-password">
	    <div class="yzm">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
	    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
	    <input type="password" name="password"  placeholder="确认密码" class="login-name">
	    <input type="button" class="login-btn" value="立即提交">
	</body>
</html>

super/templates/user/gladdress.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		
	</head>
	<body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">管理收货地址</a>
            </h1>
            <div class="am-header-right am-header-nav">
				<a href="address.html" class="">
					<i class="am-icon-plus"></i>
				</a>
			</div>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="address-list">
	    	<li class="curr">
	    		<p>收货人：徐女士&nbsp;&nbsp;182********</p>
	    		<p class="order-add1">收货地址：江西省南昌市 青云谱区解放西路258号江西省南昌市 青云谱区解放西路258号</p>
	    	    <hr />
	    	    <div class="address-cz">
	    	    	<label class="am-radio am-warning">
                       <input type="radio" name="radio3" value="" data-am-ucheck checked> 设为默认
                    </label>
                    <a href=""><img src="images/bj.png" width="18" />&nbsp;编辑</a>
                    <a href="">删除</a>
	    	    </div>
	    	</li>
	    	<li>
	    		<p>收货人：徐女士&nbsp;&nbsp;182********</p>
	    		<p class="order-add1">收货地址：江西省南昌市 青云谱区解放西路258号江西省南昌市 青云谱区解放西路258号</p>
	    	    <hr />
	    	    <div class="address-cz">
	    	    	<label class="am-radio am-warning">
                       <input type="radio" name="radio3" value="" data-am-ucheck > 设为默认
                    </label>
                    <a href=""><img src="images/bj.png" width="18" />&nbsp;编辑</a>
                    <a href="">删除</a>
	    	    </div>
	    	</li>
	    	<li>
	    		<p>收货人：徐女士&nbsp;&nbsp;182********</p>
	    		<p class="order-add1">收货地址：江西省南昌市 青云谱区解放西路258号江西省南昌市 青云谱区解放西路258号</p>
	    	    <hr />
	    	    <div class="address-cz">
	    	    	<label class="am-radio am-warning">
                       <input type="radio" name="radio3" value="" data-am-ucheck > 设为默认
                    </label>
                    <a href=""><img src="images/bj.png" width="18" />&nbsp;编辑</a>
                    <a href="">删除</a>
	    	    </div>
	    	</li>
	    	<li>
	    		<p>收货人：徐女士&nbsp;&nbsp;182********</p>
	    		<p class="order-add1">收货地址：江西省南昌市 青云谱区解放西路258号江西省南昌市 青云谱区解放西路258号</p>
	    	    <hr />
	    	    <div class="address-cz">
	    	    	<label class="am-radio am-warning">
                       <input type="radio" name="radio3" value="" data-am-ucheck > 设为默认
                    </label>
                    <a href=""><img src="images/bj.png" width="18" />&nbsp;编辑</a>
                    <a href="">删除</a>
	    	    </div>
	    	</li>
	    </ul>
<script src="js/jquery.min.js"></script>
<script src="js/amazeui.min.js"></script> 
	</body>
</html>

super/templates/user/integral.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<script src="js/jquery-1.10.2.min.js"></script>
		<script src="js/time.js"></script>
	</head>
	<body style="background: #efefef;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">积分</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="record-ye">
	   	  <p>当前积分</p>
	   	  <b>10</b>
	    </div>
	    <div class="re-chong">
	      <a href="integralexchange.html"><img src="images/gift.png" width="22"/><span>兑换</span></a>
	    </div>
	    <ul class="money-out">
	    	<li class="current"><a href="">获得</a></li>
	    	<li><a href="integralexchange.html">兑换</a></li>
	    </ul>
	    <ul class="out-list">
	    	<li>
	    		<img src="images/candar.png" width="30" />
	    		<span>
	    			<p>签到送积分</p>
	    			<p style="color: #a4a4a4; font-size: 1.4rem;">2016-01-07 16:34:20</p>
	    		</span>
	    		<i>+5</i>
	    	</li>
	    	<li>
	    		<img src="images/candar.png" width="30" />
	    		<span>
	    			<p>签到送积分</p>
	    			<p style="color: #a4a4a4; font-size: 1.4rem;">2016-01-07 16:34:20</p>
	    		</span>
	    		<i>+5</i>
	    	</li>
	    </ul>
	    
	    <script src="js/jquery.min.js"></script>
        <script src="js/amazeui.min.js"></script>
	</body>
</html>

super/templates/user/login.html
{% extends 'common/parent.html' %}
{% load static %}
{% block title %}
    登录
{% endblock %}


{% block content %}
    <form action="" method="post" class="am-form-horizontal">
        {% csrf_token %}
        <input type="text" name="phone" id="mobile" value="{{ request.POST.user_name }}" placeholder="请输入用户名/手机号"
               class="login-name">
        <p class="am-text-danger">{{ form.errors.phone.0 }}</p>

        <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <input type="submit" class="login-btn" value="我要登录">
        <div class="agree">
            <a href="{% url 'user:注册' %}">免费注册</a>
            <a href="forgetpassword.html" class="forget">忘记密码？</a>
        </div>
        <div class="line"></div>
        <div class="line-text">第三方账号登录</div>
        <ul class="second-login">
            <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
            <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
        </ul>
    </form>
{% endblock %} 

super/templates/user/myrecommend.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>超市</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="renderer" content="webkit">
        <meta http-equiv="Cache-Control" content="no-siteapp" />
        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">
		<link href="css/amazeui.min.css" rel="stylesheet" type="text/css" />
		<link href="css/style.css" rel="stylesheet" type="text/css" />
		<link href="css/check.css" rel="stylesheet" type="text/css" />
	</head>
	<body style=" background: #efefef;">
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">我的推荐</a>
            </h1>
            
	    </header>
	    <div style="height: 49px;"></div>
	   <div class="hotline" style="overflow: hidden;">
	   	 <span style="width: 70%;">被推荐人</span>
	   	 <span style="width: 30%;">时间</span>
	   </div>
	   <ul class="application" style="margin-top: 0;">
	   	 <li>
	   	 	<a href="">
	   	 		<img src="images/my.png" width="45"/>
	   	 		<span>
	   	 			<p style="margin-top: 1rem;">薰兜茶</p>
	   	 		</span>
	   	 		<i style="color: #4c4c4c;">2016-01-05</i>
	   	 	</a>
	   	 </li>
	   	 <li>
	   	 	<a href="">
	   	 		<img src="images/my.png" width="45" />
	   	 		<span>
	   	 			<p style="margin-top: 1rem;">胡语歌颜</p>
	   	 		</span>
	   	 		<i style="color: #4c4c4c;">2016-01-05</i>
	   	 	</a>
	   	 </li>
	   	
	   </ul>
	</body>
</html>